
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appGestor
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: bdGestor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestorincidencias
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

